// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDCAGQ1DMuY-p83eaQLn9-9Q2Q5ZGsI8',
    appId: '1:555793029436:web:43e830f4f7eee0b181a639',
    messagingSenderId: '555793029436',
    projectId: 'smartcleancity-30ebc',
    authDomain: 'smartcleancity-30ebc.firebaseapp.com',
    storageBucket: 'smartcleancity-30ebc.firebasestorage.app',
    measurementId: 'G-170RN4CDDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtygKXdKrQlQKlmrnV9bkZvCPEqzJ0SU',
    appId: '1:555793029436:android:61aa4eb9f765b6ca81a639',
    messagingSenderId: '555793029436',
    projectId: 'smartcleancity-30ebc',
    storageBucket: 'smartcleancity-30ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGuPKa1f8svw-SaayrrOz-jpxk50MkV4',
    appId: '1:555793029436:ios:05d414370fe03f4281a639',
    messagingSenderId: '555793029436',
    projectId: 'smartcleancity-30ebc',
    storageBucket: 'smartcleancity-30ebc.firebasestorage.app',
    iosBundleId: 'com.example.smartclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGuPKa1f8svw-SaayrrOz-jpxk50MkV4',
    appId: '1:555793029436:ios:05d414370fe03f4281a639',
    messagingSenderId: '555793029436',
    projectId: 'smartcleancity-30ebc',
    storageBucket: 'smartcleancity-30ebc.firebasestorage.app',
    iosBundleId: 'com.example.smartclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHDCAGQ1DMuY-p83eaQLn9-9Q2Q5ZGsI8',
    appId: '1:555793029436:web:a7138719cd793b6981a639',
    messagingSenderId: '555793029436',
    projectId: 'smartcleancity-30ebc',
    authDomain: 'smartcleancity-30ebc.firebaseapp.com',
    storageBucket: 'smartcleancity-30ebc.firebasestorage.app',
    measurementId: 'G-NB32V3C33E',
  );
}
